title: Marc Faber # your name (or website title) here
logo: "/images/dummy.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ...under... 
  <br><br>
  ...construction...
  <br><br>
  <a href="https://www.xing.com/profile/Marc_Faber11">View My XING Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
