title: Marc Faber # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Software Developer at<br>
  GenoData EDV-Systeme GmbH<br>
  Germany<br>
  <br>
  <a href="https://www.xing.com/profile/Marc_Faber11">View My XING Profile</a> 
  <br>
  <a href="https://www.linkedin.com/in/marc-faber">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-6549905-1 # your Google Analytics tracking ID here
